//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtroomProject.COURTER
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class courtroom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public courtroom()
        {
            this.DistrictCourts = new HashSet<DistrictCourt>();
        }
    
        public int Room_ID { get; set; }
        [Required(ErrorMessage = "Required")]
        public string location_cr { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Phone_no_cr { get; set; }
        [Required(ErrorMessage = "Required")]
        public string case_t { get; set; }
        public Nullable<int> Plaintiff { get; set; }
        public Nullable<int> Defendant_ID { get; set; }
        public Nullable<int> Spec_ID { get; set; }
        public Nullable<int> Clerk_ID { get; set; }
        public Nullable<int> Judge_ID { get; set; }
        public Nullable<int> Sheriff_ID { get; set; }
        public Nullable<int> Member_ID { get; set; }
    
        public virtual Clerk Clerk { get; set; }
        public virtual Defendant Defendant { get; set; }
        public virtual Judge Judge { get; set; }
        public virtual Jury Jury { get; set; }
        public virtual Plaintiff Plaintiff1 { get; set; }
        public virtual Sheriff Sheriff { get; set; }
        public virtual spectator spectator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistrictCourt> DistrictCourts { get; set; }
    }
}
