//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtroomProject.COURTER
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DistrictCourt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistrictCourt()
        {
            this.HighCourts = new HashSet<HighCourt>();
        }
    
        public int ID_DC { get; set; }
        [Required(ErrorMessage = "Required")]
        public string District { get; set; }
        [Required(ErrorMessage = "Required")]
        public string address { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Phone_no_dc { get; set; }

        public string Email { get; set; }
        public Nullable<int> Room_ID { get; set; }
    
        public virtual courtroom courtroom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HighCourt> HighCourts { get; set; }
    }
}
