//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtroomProject.COURTER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourtEntities : DbContext
    {
        public CourtEntities()
            : base("name=CourtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clerk> Clerks { get; set; }
        public virtual DbSet<courtroom> courtrooms { get; set; }
        public virtual DbSet<Defendant> Defendants { get; set; }
        public virtual DbSet<DistrictCourt> DistrictCourts { get; set; }
        public virtual DbSet<firm> firms { get; set; }
        public virtual DbSet<HighCourt> HighCourts { get; set; }
        public virtual DbSet<Judge> Judges { get; set; }
        public virtual DbSet<Jury> Juries { get; set; }
        public virtual DbSet<lawyer> lawyers { get; set; }
        public virtual DbSet<Plaintiff> Plaintiffs { get; set; }
        public virtual DbSet<Sheriff> Sheriffs { get; set; }
        public virtual DbSet<spectator> spectators { get; set; }
    }
}
