//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtroomProject.COURTER
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class firm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public firm()
        {
            this.Judges = new HashSet<Judge>();
            this.lawyers = new HashSet<lawyer>();
        }
    
        public int Firm_ID { get; set; }
        [Required(ErrorMessage = "Required")]
        public string name_firm { get; set; }
        [Required(ErrorMessage = "Required")]
        public string address_firm { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> phone_firm { get; set; }
        [Required(ErrorMessage = "Required")]
        public string email_firm { get; set; }
        public Nullable<System.DateTime> StartingYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Judge> Judges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lawyer> lawyers { get; set; }
    }
}
