//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourtroomProject.COURTER
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HighCourt
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Required")]
        public string ChiefJustice { get; set; }
        [Required(ErrorMessage = "Required")]
        public string address { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Phoneno { get; set; }
        [Required(ErrorMessage = "Required")]
        public string email { get; set; }
        public Nullable<int> ID_DC { get; set; }
    
        public virtual DistrictCourt DistrictCourt { get; set; }
    }
}
