//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


//Thi is the class for the program Usman hamid 

namespace CourtroomProject.COURTER
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class spectator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public spectator()
        {
            this.courtrooms = new HashSet<courtroom>();
        }
    
        public int Spec_ID { get; set; }
        [Required(ErrorMessage ="Required")]
        public string Name_spec { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<System.DateTime> DOB_Spec { get; set; }
        public string address_spec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<courtroom> courtrooms { get; set; }
    }
}
